import type { Metadata } from "next";
import { Inria_Sans } from "next/font/google";
import "./globals.css";

const inriaSans = Inria_Sans({
 weight: ["300", "400", "700"],
 subsets: ["latin"],
 variable: "--font-inria-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inriaSans.className} ${inriaSans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
